export const Questions = [
  {
    image: "https://video-images.vice.com/articles/5d8bb2bc9efced000809b6ff/lede/1569436455709-k9yitoot6xjxqgsvjcuq.jpeg?crop=1xw:1xh;center,center&resize=1200:*",
    prompt: "What is the name of the final course of all 'Mario Kart' video games?",
    optionA: "Hotdog Hotrod",
    optionB: "Sunset Boulevard",
    optionC: "Highway Pieway",
    optionD: "Rainbow Road",
    answer: "optionD",
  },
  {
    image: "https://cdn.vox-cdn.com/thumbor/XrQ1hlHUj8-ok5nWOZQBiWAzJxA=/85x0:1014x619/1200x800/filters:focal(85x0:1014x619)/cdn.vox-cdn.com/uploads/chorus_image/image/29585969/mgsvgz_ss_demo_002.0.jpg",
    prompt: "Solid Snake is the hero of the famous video game franchise?",
    optionA: "Gears",
    optionB: "Splinter Cell",
    optionC: "Grand Theft Auto",
    optionD: "The Metal Gear",
    answer: "optionD",
  },
  {
    image: "https://cdn2.unrealengine.com/Fortnite%2Fblog%2Fseason-8%2FBR08_News_Featured_Launch_ScreenKeyArt_Announce-1920x1080-f831323339109ab3c6a8d9e4c670f1973b8796d0.jpg",
    prompt: "Which famous video game franchise is the game 'V-Bucks' from?",
    optionA: "Forknife",
    optionB: "Fortnyte",
    optionC: "Fortnite",
    optionD: "Fortnight",
    answer: "optionC",
  },
  {
    image: "https://wallpapercave.com/wp/wp2866504.png",
    prompt: "Mario originated as a character in which video game?",
    optionA: "Dragon Quest",
    optionB: "Tetris",
    optionC: "Donkey Kong",
    optionD: "The Legend of Zelda",
    answer: "optionC",
  },
  {
    image: "https://cdn.images.express.co.uk/img/dynamic/143/590x/1444927_1.jpg",
    prompt: "Nintendo began as a company that sold which products?",
    optionA: "Arcade Machines",
    optionB: "Nintendo Wii",
    optionC: "Playing Cards",
    optionD: "Battling Coins",
    answer: "optionC",
  },
  {
    image: "https://cdn1.dotesports.com/wp-content/uploads/2019/10/07224923/call-of-duty-mobile-1-1.jpg",
    prompt: "In 'Call of Duty: Advanced Warfare,' what's the name of Jack Mitchell's best friend?",
    optionA: "Marcus Holloway",
    optionB: "Sam Fisher",
    optionC: "Jason Brody",
    optionD: "Will Irons",
    answer: "optionD",
  },
  {
    image: "https://images3.alphacoders.com/269/thumb-1920-269937.jpg",
    prompt: "Who is the first character you play in 'Injustice 2?'",
    optionA: "Superman",
    optionB: "Batman",
    optionC: "The Joker",
    optionD: "Wonder Woman",
    answer: "optionB",
  },
  {
    image: "https://img.memecdn.com/follow-the-damn-train-cj_o_6263953.jpg",
    prompt: "What was the first video game in the world called?",
    optionA: "Pong",
    optionB: "Flappy",
    optionC: "Tetris",
    optionD: "Snake",
    answer: "optionA",
  },
  {
    image: "https://www.shutupandtakemymoney.com/wp-content/uploads/2020/04/quarantined-dads-busting-out-old-games-meme-300x250.jpg",
    prompt: "What's the best selling video game console of all time?",
    optionA: "Playstation",
    optionB: "Xbox 360",
    optionC: "Playstation 2",
    optionD: "Xbox",
    answer: "optionC",
  },
  {
    image: "https://lh3.googleusercontent.com/proxy/blGdhZiQ7nR3k5gydg4-Dik7zGn1daMiGfMMHW5iGNV9z6-3EJ4Wp8VCcXoGhjgDfff0G9HpWex9t3hNNPqMWA9eSQniynavIuyhYew3dJA",
    prompt: "Which game was published by GT Interactive in 1996?",
    optionA: "Quake",
    optionB: "Driver",
    optionC: "Doom",
    optionD: "Blood",
    answer: "optionA",
  },
  {
    image: "https://cdn.mos.cms.futurecdn.net/Usdru3W58p6g8NGpxzUfyi.jpg",
    prompt: "What's the best selling video game of all time?",
    optionA: "Red Dead Redemption 2",
    optionB: "GTA IV",
    optionC: "Minecraft",
    optionD: "GTA San Andreas",
    answer: "optionC",
  },
  {
    image: "https://gamingbolt.com/wp-content/uploads/2010/10/shrek-4-1280x720.jpeg",
    prompt: "The reference to the 'stolen sweet troll' was a running joke with which game developer?",
    optionA: "EA",
    optionB: "Bethesda",
    optionC: "Capcom",
    optionD: "Ubisoft",
    answer: "optionB",
  }, 
  {
    image: "https://i.ibb.co/2sfkFTH/Banner233253-1-5-2-1.png",
    prompt: "Blizzard Entertainment is best known for which video game franchise?",
    optionA: "Diablo",
    optionB: "Overwatch",
    optionC: "World of Warcraft",
    optionD: "Starcraft",
    answer: "optionC",
  },
  {
    image: "https://www.wikihow.com/images/thumb/9/93/Play-Better-at-Pac-Man-Step-4.jpg/v4-460px-Play-Better-at-Pac-Man-Step-4.jpg.webp",
    prompt: "What kind of food was the character Pac Man modelled on?",
    optionA: "An Apple",
    optionB: "A Pizza",
    optionC: "A Pie",
    optionD: "A Sausage",
    answer: "optionB",
  },
  {
    image: "https://cdn.vox-cdn.com/thumbor/SJSNuaze4TWx6w8Jew0rsergM1E=/0x267:2040x1287/fit-in/1200x600/cdn.vox-cdn.com/uploads/chorus_asset/file/16134777/jbareham_190412_ply0871_game_boy_0117.jpg",
    prompt: "What role did the creator of the Game Boy originally hold at Nintendo?",
    optionA: "Janitor",
    optionB: "Manager",
    optionC: "Maintenance",
    optionD: "Programmer",
    answer: "optionA",
  },
  {
    image: "https://staticg.sportskeeda.com/editor/2020/11/a150d-16045288475620-800.jpg",
    prompt: "What's a Charged Creeper?",
    optionA: "A headset that has been charged overnight.",
    optionB: "A random child who joined your lobby.",
    optionC: "A creeper that was struck with lightning.",
    optionD: "A creeper inside your house.",
    answer: "optionC",
  },
  {
    image: "https://staticctf.akamaized.net/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/MnLnHV7TKYLvynbypV9Fu/7b0387d2e8856134c8a401dcd15f42ca/farcry3_cover_desktop_137015.jpg",
    prompt: "Which of the following characters are not in Far Cry 3?",
    optionA: "Jason Brodey",
    optionB: "Vaas Montenegro",
    optionC: "Agatha Earnhardt",
    optionD: "Sam Becker",
    answer: "optionC",
  },
];