//Quiz questions and answers needed for our application
export const Questions = [
  {
    prompt: "Solid Snake is the main protagonist of which famous video game franchise?",
    optionA: "Gears",
    optionB: "Splinter Cell",
    optionC: "Grand Theft Auto",
    optionD: "The Metal Gear",
    answer: "optionD",
  },
  {
    prompt: "What happens to Diana Burnwood at the end of Hitman: Absolution?",
    optionA: "She Dies",
    optionB: "She Kills Victoria",
    optionC: "Victoria Dies",
    optionD: "She Lives",
    answer: "optionD",
  },
  {
    prompt: "In the Assassins Creed franchise, which of the following is Altair's son?",
    optionA: "Connor",
    optionB: "Henry",
    optionC: "Sef",
    optionD: "Tamir",
    answer: "optionC",
  },
  {
    prompt: "In 'Grand Theft Auto IV', who does Niko Bellic have to choose between in the end?",
    optionA: "Michelle and Kate",
    optionB: "Roman and Kate",
    optionC: "Roman and Jacob",
    optionD: "Roman and Patrick",
    answer: "optionB",
  },
  {
    prompt: "In 'Call of Duty: Advanced Warfare,' what's the name of Jack Mitchell's best friend?",
    optionA: "Marcus Holloway",
    optionB: "Sam Fisher",
    optionC: "Jason Brody",
    optionD: "Will Irons",
    answer: "optionD",
  },
  {
    prompt: "What is the name of the final course in the 'Mario Kart' video games?",
    optionA: "Hotdog Hotrod",
    optionB: "Sunset Boulevard",
    optionC: "Highway Pieway",
    optionD: "Rainbow Road",
    answer: "optionD",
  },
  {
    prompt: "In 'Medal of Honor: Vanguard', who are the American's fighting against?",
    optionA: "The Nazi's",
    optionB: "The Koreans",
    optionC: "The French",
    optionD: "The UK",
    answer: "optionA",
  },
  {
    prompt: "What was the first video game in the world called?",
    optionA: "Pong",
    optionB: "Flappy",
    optionC: "Tetris",
    optionD: "Snake",
    answer: "optionA",
  },
  {
    prompt: "In Life is Strange 2, what ability does Daniel have?",
    optionA: "Flight",
    optionB: "Telekenesis",
    optionC: "Time Travel",
    optionD: "Mind Control",
    answer: "optionB",
  },
  {
    prompt: "What is Crash Bandicoot's companions name?",
    optionA: "Aku Aku",
    optionB: "Uka Uka",
    optionC: "Kau Kau",
    optionD: "Aka Aka",
    answer: "optionA",
  },
  {
    prompt: "In Red Dead Redemption 2, what disease does Arthur have?",
    optionA: "Scarlet Fever",
    optionB: "Dysentery",
    optionC: "Cholera",
    optionD: "Tuberculosis",
    answer: "optionD",
  },
  {
    prompt: "The reference 'stolen sweetroll' is a running joke from which game franchise?",
    optionA: "Fallout",
    optionB: "Skyrim",
    optionC: "Outer Worlds",
    optionD: "Elder Scrolls",
    answer: "optionA",
  }, 
  {
    prompt: "Which of the following characters are not in Far Cry 3?",
    optionA: "Jason Brodey",
    optionB: "Vaas Montenegro",
    optionC: "Agatha Earnhardt",
    optionD: "Sam Becker",
    answer: "optionC",
  },
  {
    prompt: "Blizzard Entertainment is best known for which video game franchise?",
    optionA: "Diablo",
    optionB: "Overwatch",
    optionC: "World of Warcraft",
    optionD: "Starcraft",
    answer: "optionC",
  },
  {
    prompt: "What was the character Pac Man based on?",
    optionA: "An Apple",
    optionB: "A Pizza",
    optionC: "A Pie",
    optionD: "A Plate",
    answer: "optionB",
  },
  {
    prompt: "What is the name of Jessica Riley's boyfriend in Until Dawn?",
    optionA: "Sam",
    optionB: "Mike",
    optionC: "Ted",
    optionD: "Josh",
    answer: "optionB",
  },
  {
    prompt: "In Far Cry 4, what is Pagan Min's sister's name?",
    optionA: "Yuma",
    optionB: "Amita",
    optionC: "Pagani",
    optionD: "None of the above",
    answer: "optionD",
  },
  {
    prompt: "In the Spyro the Dragon franchise, what color is Cynder's horns?",
    optionA: "Green",
    optionB: "Purple",
    optionC: "White",
    optionD: "Yellow",
    answer: "optionC",
  },
  {
    prompt: "In Tomb Raider: Survivor, what does Lara initially fall into?",
    optionA: "Porcupine Needle",
    optionB: "Rusted Bar",
    optionC: "Broken Bone",
    optionD: "Rusted Spear",
    answer: "optionB",
  },
  {
    prompt: "What is the first car brand that you get to drive in Need For Speed: Most Wanted?",
    optionA: "BMW",
    optionB: "Ford",
    optionC: "Honda",
    optionD: "Subaru",
    answer: "optionA",
  },
];